version: "3"
services:
  postgres:
    image: postgres:14.5-alpine
    environment:
      POSTGRES_USER: ${POSTGRES_USER:-postgres}
      # POSTGRES_PASSWORD: ${POSTGRES_PASSWORD:-password}
      POSTGRES_HOST_AUTH_METHOD: trust
      POSTGRES_DB: postgres
    volumes:
      - ./init-schema.sh:/docker-entrypoint-initdb.d/init-schema.sh
      # - ./data/postgres:/var/lib/postgresql/data
    ports:
      - "5432:5432"
  keycloak:
    image: quay.io/keycloak/keycloak:20.0.2
    environment:
      KEYCLOAK_ADMIN: admin
      KEYCLOAK_ADMIN_PASSWORD: admin
    ports:
      - "8082:8082"
    command: start-dev --http-port=8082
    profiles:
      - extra
