#!/bin/bash
set -e

POSTGRES_SCHEMA=${POSTGRES_SCHEMA:-chore}

psql -v ON_ERROR_STOP=1 --username "$POSTGRES_USER" --dbname "$POSTGRES_DB" <<-EOSQL
    CREATE SCHEMA IF NOT EXISTS ${POSTGRES_SCHEMA};
EOSQL

set +e
